<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Kontak Kami</title>';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">';
echo '</head>';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<!-- Navbar content -->';
echo '</nav>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<a class="navbar-brand" href="#">CoffeShop</a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item active">';
echo '<a class="nav-link" href="website.html">Beranda</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="tentangkami.html">Tentang Kami</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="menu.html">Menu</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="kontak.html">Kontak</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container my-5">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<h2>Kontak Kami</h2>';
echo '<p>Jangan ragu untuk menghubungi kami melalui informasi kontak di bawah ini:</p>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<h3>Informasi Kontak</h3>';
echo '<p><strong>Alamat:</strong> Jl.A.P. Pettarani No. 123, Kota Makassar</p>';
echo '<p><strong>Email:</strong> info@CoffeShop.com</p>';
echo '<p><strong>Telepon:</strong> (123) 456-7890</p>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<h3>Formulir Kontak</h3>';
echo '<form>';
echo '<div class="form-group">';
echo '<label for="nama">Nama:</label>';
echo '<input type="text" class="form-control" id="nama" placeholder="Masukkan nama">';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="email">Email:</label>';
echo '<input type="email" class="form-control" id="email" placeholder="Masukkan email">';
echo '</div>';
echo '<div class="form-group">';
echo '<label for="pesan">Pesan:</label>';
echo '<textarea class="form-control" id="pesan" rows="5" placeholder="Masukkan pesan"></textarea>';
echo '</div>';
echo '<button type="submit" class="btn btn-primary">Kirim Pesan</button>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<footer class="bg-dark text-white text-center py-3">';
echo '<p>&copy; 2023 CoffeShop</p>';
echo '</footer>';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>';
echo '</body>';
echo '</html>';
?>