<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Menu Kopi dan Makanan</title>';
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">';
echo '</head>';
echo '<body>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<!-- Navbar content -->';
echo '</nav>';
echo '<nav class="navbar navbar-expand-lg navbar-dark bg-dark">';
echo '<a class="navbar-brand" href="#">CoffeShop</a>';
echo '<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">';
echo '<span class="navbar-toggler-icon"></span>';
echo '</button>';
echo '<div class="collapse navbar-collapse" id="navbarNav">';
echo '<ul class="navbar-nav ml-auto">';
echo '<li class="nav-item active">';
echo '<a class="nav-link" href="website.html">Beranda</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="tentangkami.html">Tentang Kami</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="menu.html">Menu</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" href="kontak.html">Kontak</a>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="container my-5">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<h2>Menu</h2>';
echo '<ul class="nav nav-tabs" id="menuTab" role="tablist">';
echo '<li class="nav-item">';
echo '<a class="nav-link active" id="kopi-tab" data-toggle="tab" href="#kopi" role="tab" aria-controls="kopi" aria-selected="true">Kopi</a>';
echo '</li>';
echo '<li class="nav-item">';
echo '<a class="nav-link" id="makanan-tab" data-toggle="tab" href="#makanan" role="tab" aria-controls="makanan" aria-selected="false">Makanan</a>';
echo '</li>';
echo '</ul>';
echo '<div class="tab-content" id="menuTabContent">';
echo '<div class="tab-pane fade show active" id="kopi" role="tabpanel" aria-labelledby="kopi-tab">';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="kopi1.jpeg" class="card-img-top" alt="Espresso">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Espresso</h5>';
echo '<p class="card-text">Kopi dengan rasa kuat dan pekat, cocok untuk pencinta kopi sejati.</p>';
echo '<span class="badge badge-primary">Rp 20,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="kopi2.jpeg" class="card-img-top" alt="Cappuccino">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Cappuccino</h5>';
echo '<p class="card-text">Kopi dengan kombinasi sempurna antara espresso, susu, dan busa susu.</p>';
echo '<span class="badge badge-primary">Rp 25,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="kopi3.jpeg" class="card-img-top" alt="Latte">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Latte</h5>';
echo '<p class="card-text">Kopi dengan susu yang lembut dan rasa kopi yang lezat.</p>';
echo '<span class="badge badge-primary">Rp 23,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tab-pane fade" id="makanan" role="tabpanel" aria-labelledby="makanan-tab">';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="makanan1.jpeg" class="card-img-top" alt="Makanan 1">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Croissant</h5>';
echo '<p class="card-text">Pastry yang populer sebagai hidangan khas di Prancis yang berbentuk bulan sabit.</p>';
echo '<span class="badge badge-primary">Rp 30,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="makanan2.jpeg" class="card-img-top" alt="Makanan 2">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Pancake</h5>';
echo '<p class="card-text">Pancake adalah sajian klasik yang terbuat dari adonan tepung terigu, telur, susu, dan baking powder yang digoreng hingga matang.</p>';
echo '<span class="badge badge-primary">Rp 35,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="card">';
echo '<img src="makanan3.jpeg" class="card-img-top" alt="Makanan 3">';
echo '<div class="card-body">';
echo '<h5 class="card-title">Sandwich</h5>';
echo '<p class="card-text">Sandwich adalah makanan yang terdiri dari dua atau lebih potongan roti yang diisi dengan berbagai macam bahan seperti daging, keju, sayuran, saus, atau lainnya.</p>';
echo '<span class="badge badge-primary">Rp 25,000</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<footer class="bg-dark text-white text-center py-3">';
echo '<p>&copy; 2023 CoffeShop</p>';
echo '</footer>';
echo '';
echo '<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>';
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>';
echo '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>';
echo '</body>';
echo '</html>';
?>